// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuDM_ntPufGqvypOef0rUF-StxZNtHIBI',
    appId: '1:406490947205:web:1b8c800e71be4df08dd3ec',
    messagingSenderId: '406490947205',
    projectId: 'tm-pbm-firebase',
    authDomain: 'tm-pbm-firebase.firebaseapp.com',
    storageBucket: 'tm-pbm-firebase.firebasestorage.app',
    measurementId: 'G-H71JTV23SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIQ8tMAKr9Ktpw10lw95Yi9fnE4P2vtcw',
    appId: '1:406490947205:android:ce9d21b219f21fda8dd3ec',
    messagingSenderId: '406490947205',
    projectId: 'tm-pbm-firebase',
    storageBucket: 'tm-pbm-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSWHVbcOo32cfmxiEtXBJ12hgMPfK9rew',
    appId: '1:406490947205:ios:687d865f70de2f298dd3ec',
    messagingSenderId: '406490947205',
    projectId: 'tm-pbm-firebase',
    storageBucket: 'tm-pbm-firebase.firebasestorage.app',
    androidClientId: '406490947205-86l9estsss737jtjq0t0cu5f6i7ggn0t.apps.googleusercontent.com',
    iosClientId: '406490947205-9e47fri25rudgc1t1rdlib0kvclpdg4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugasPbmTm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSWHVbcOo32cfmxiEtXBJ12hgMPfK9rew',
    appId: '1:406490947205:ios:687d865f70de2f298dd3ec',
    messagingSenderId: '406490947205',
    projectId: 'tm-pbm-firebase',
    storageBucket: 'tm-pbm-firebase.firebasestorage.app',
    androidClientId: '406490947205-86l9estsss737jtjq0t0cu5f6i7ggn0t.apps.googleusercontent.com',
    iosClientId: '406490947205-9e47fri25rudgc1t1rdlib0kvclpdg4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugasPbmTm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuDM_ntPufGqvypOef0rUF-StxZNtHIBI',
    appId: '1:406490947205:web:aeddd7bd88720c798dd3ec',
    messagingSenderId: '406490947205',
    projectId: 'tm-pbm-firebase',
    authDomain: 'tm-pbm-firebase.firebaseapp.com',
    storageBucket: 'tm-pbm-firebase.firebasestorage.app',
    measurementId: 'G-18PEESTQMG',
  );

}